spring:
  profiles:
    group:
      "local": "localDB, common"
      "server": "serverDB, common"

    default: "local" # active profile

---
spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    url: jdbc:mariadb://localhost:3306/walking
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111

---
spring:
  config:
    activate:
      on-profile: "serverDB"

  datasource:
    url: jdbc:mariadb://madcamp-db.craceskswxlk.ap-northeast-2.rds.amazonaws.com:3306/walking
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: Eorlftkfkdgo

---
spring:
  config:
    activate:
      on-profile: "common"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace # show parameter binding
      SQL: DEBUG

security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: 7693c7ea77cba3d6df49d240e34979c4
          redirect-uri: "http://localhost:8080/api/v1/kakao/authenticate"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: account_email
          client-name: Kakao
      provider:
        kakao:
          authorization_uri: https://kauth.kakao.com/oauth/authorize
          token_uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user_name_attribute: id

application:
  security:
    jwt:
      secret-key: bG9uZG9uYnJpZGdlZ29vZGx1Y2tnb29kZnV0dXJlZ29vZGRheWhlbGxvbW90aGVyZnVja2Vy
      expiration: 86400000 # a day
      refresh-token:
        expiration: 31536000000 # 365 days


social:
  kakao:
    token_uri: "https://kauth.kakao.com/oauth/token"
    redirect_uri: "http://localhost:8080/api/kakao/authenticate/v1"
    grant_type: "authorization_code"
    client_id: "7693c7ea77cba3d6df49d240e34979c4"


cloud:
  aws:
    s3:
      bucket: bridge-image-storage
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false