spring:
  profiles:
    group:
      "local": "localDB, common"
      "server": "serverDB, common"

    default: "local" # active profile

---
spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    url: jdbc:mariadb://localhost:3306/walking
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111

---
spring:
  config:
    activate:
      on-profile: "serverDB"

  datasource:
    url: jdbc:mariadb://madcamp-db.craceskswxlk.ap-northeast-2.rds.amazonaws.com:3306/walking
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: Eorlftkfkdgo

---
spring:
  config:
    activate:
      on-profile: "common"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace # show parameter binding
      SQL: DEBUG

application:
  security:
    jwt:
      secret-key: bG9uZG9uYnJpZGdlZ29vZGx1Y2tnb29kZnV0dXJlZ29vZGRheWhlbGxvbW90aGVyZnVja2Vy
      expiration: 86400000 # a day
      refresh-token:
        expiration: 31536000000 # 365 days

cloud:
  aws:
    s3:
      bucket: wona-s3
    region:
      static: ap-northeast-2
    credentials:
      secret-key: CYXVqvqLti5Fck3+MzFOpqYQ2nm5Kjy3f9lQIcgC
      access-key: AKIAT7A43HYIMXFACMMB